# -*- coding: utf-8 -*-
"""predict_wellness

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mrW6GJoh38ivKtwPv61dvVZ3zvYXNQsR
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install koreanize-matplotlib
import koreanize_matplotlib

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import os

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/daily_habits.csv')
df['date'] = pd.to_datetime(df['date'])

x = df[['exercise', 'study', 'health', 'self_care', 'diet']].astype(float)
y = df['wellness_score'].astype(float)

model = LinearRegression()
model.fit(x,y)

y_pred = model.predict(x)
mse = mean_squared_error(y, y_pred)
r2 = r2_score(y, y_pred)

plt.figure(figsize = (10,6))
plt.plot(df['date'], y, label = '실제 값', marker = 'o')
plt.plot(df['date'], y_pred, label = '예측 값', marker = 'x')
plt.xlabel('날짜')
plt.ylabel('웰빙 점수 (0~10)')
plt.title('웰빙 점수 예측 vs 실제 (2025년 7월)')
plt.legend()
plt.grid(True)
plt.tight_layout()